# Lang
language: en

# Header
menu:
  Home: /
  Archives: /archives
  Website: /websites
  About: /about
rss: /atom.xml

# Content
fancybox: true

# highlight.js
highlight:
    style: tomorrow-night-eighties


# Miscellaneous
google_analytics: UA-92533917-1
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: LuoXiaojie
description: To be a Full Stack Engineer.
links:
  Blog: /archives
  GitHub: https://github.com/xiaojieluo
  # Instagram: http://instagram.com/
  Facebook: https://www.facebook.com/cufrancis
  Twitter : https://twitter.com/luoxiaojieff


# Info
archive_footer_content: Archive.
post_footer_content: Post.
